(() => {
  'use strict';
  const STORAGE_KEY = 'wortwerk-library-v1';
  const palette = [
    ['#E76F51','Terrakotta'],['#DC2626','Rot'],['#F97316','Orange'],['#D97706','Bernstein'],
    ['#EAB308','Gelb'],['#65A30D','Oliv'],['#16A34A','Grün'],['#15803D','Waldgrün'],
    ['#0F766E','Petrol'],['#14B8A6','Türkis'],['#0891B2','Cyan'],['#0284C7','Himmelblau'],
    ['#2563EB','Blau'],['#1D4ED8','Kobaltblau'],['#1E3A8A','Marineblau'],['#475569','Graphit'],
    ['#64748B','Schiefer'],['#8B5E3C','Kastanie'],['#DB2777','Pink'],['#F8FAFC','Weiß']
  ];
  const colors = palette.map(([hex])=>hex);
  const safeColor = (value,fallback=colors[0]) => typeof value==='string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
  const emojiChoices = [
    ['📚','lernen buch bücher bildung','Lernen'],['📖','buch lesen','Lernen'],['✏️','stift schreiben','Lernen'],['📝','notizen schreiben','Lernen'],['🎓','abschluss schule','Lernen'],['💡','idee wissen','Lernen'],['🧠','gehirn wissen','Lernen'],['🔬','wissenschaft labor','Lernen'],['🧪','chemie labor','Lernen'],['🧮','mathe rechnen','Lernen'],['💻','computer informatik','Lernen'],['🌍','welt erde geografie','Lernen'],
    ['🇬🇧','england flagge englisch sprache','Sprachen'],['🇫🇷','frankreich flagge französisch sprache','Sprachen'],['🇪🇸','spanien flagge spanisch sprache','Sprachen'],['🇮🇹','italien flagge italienisch sprache','Sprachen'],['🇩🇪','deutschland flagge deutsch sprache','Sprachen'],['🗣️','sprechen sprache','Sprachen'],['💬','dialog sprache','Sprachen'],['🔤','buchstaben alphabet','Sprachen'],['📜','geschichte dokument','Sprachen'],['✍️','schreiben text','Sprachen'],
    ['😀','lächeln gesicht froh','Menschen'],['😎','cool gesicht','Menschen'],['🤓','brille klug','Menschen'],['👩‍🏫','lehrerin schule','Menschen'],['👨‍🏫','lehrer schule','Menschen'],['🧑‍🎓','schüler studium','Menschen'],['❤️','herz liebe','Menschen'],['⭐️','stern','Menschen'],['🏆','pokal erfolg','Menschen'],['🎯','ziel fokus','Menschen'],
    ['🌱','pflanze wachsen natur','Natur'],['🌿','blatt natur','Natur'],['🌸','blume natur','Natur'],['🌞','sonne natur','Natur'],['🌙','mond nacht','Natur'],['🌈','regenbogen natur','Natur'],['🌊','meer wasser','Natur'],['🔥','feuer energie','Natur'],['🦋','schmetterling tier','Natur'],['🐝','biene tier','Natur'],['🐈','katze tier','Natur'],['🦉','eule tier','Natur'],
    ['⚽️','fußball sport','Aktivitäten'],['🏀','basketball sport','Aktivitäten'],['🎨','kunst malen','Aktivitäten'],['🎵','musik noten','Aktivitäten'],['🎸','gitarre musik','Aktivitäten'],['🎭','theater kunst','Aktivitäten'],['♟️','schach spiel','Aktivitäten'],['🚀','rakete weltraum','Aktivitäten'],['✈️','flugzeug reisen','Aktivitäten'],['🏛️','gebäude geschichte','Aktivitäten'],['⏳','zeit sanduhr','Aktivitäten'],['🔑','schlüssel','Aktivitäten']
  ];
  const icons = ['📚','🌐','📐','🏛️','🧪','🎨'];
  const $ = (s, root=document) => root.querySelector(s);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const id = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const initial = () => ({subjects:[],folders:[],sets:[],cards:[],recent:[],studySessions:{},studyHistory:[]});
  let data = initial(), activeSubject = null, activeFolder = null, activeSet = null, view = 'library';
  let formContext = null, importRows = [], session = null;
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}catch(e){console.warn('Lokaler Cache konnte nicht aktualisiert werden.',e)}const pending=window.WortwerkRepository.saveLibrary(data);pending.catch(()=>{});return pending}
  const subject = key => data.subjects.find(x=>x.id===key);
  const folder = key => data.folders.find(x=>x.id===key);
  const setById = key => data.sets.find(x=>x.id===key);
  const setCards = key => data.cards.filter(x=>x.setId===key).sort((a,b)=>(a.position??0)-(b.position??0));
  const subjectSets = key => data.sets.filter(x=>x.subjectId===key);
  const subjectFolders = key => data.folders.filter(x=>x.subjectId===key);
  function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2400)}
  function render(){
    renderNav();
    if(activeSet&&setById(activeSet)){renderSet();return}
    if(activeFolder&&folder(activeFolder)){renderFolder();return}
    if(activeSubject&&subject(activeSubject)){renderSubject();return}
    renderLibrary();
  }
  function renderNav(){
    document.querySelectorAll('[data-view]').forEach(button=>button.onclick=event=>{
      event.preventDefault();activeSubject=null;activeFolder=null;activeSet=null;view=button.dataset.view;render();
    });
    crumbs(view==='recent'?['Zuletzt gelernt']:['Dein Lernraum']);
  }
  function crumbs(parts){const last=parts.length-1;$('#breadcrumbs').setAttribute('aria-label','Aktueller Ort');$('#breadcrumbs').innerHTML=parts.map((part,index)=>`<span>${index===last?`<b aria-current="location">${esc(part)}</b>`:`<button type="button" class="breadcrumb-link" data-crumb-index="${index}">${esc(part)}</button>`}</span>`).join('');$('#breadcrumbs').querySelectorAll('[data-crumb-index]').forEach(button=>button.onclick=()=>{const level=Number(button.dataset.crumbIndex);if(level===0){activeSubject=null;activeFolder=null;activeSet=null;view='library'}else if(level===1){activeFolder=null;activeSet=null}else if(level===2){activeSet=null}render()})}
  function renderLibrary(){
    activeSubject=null;activeFolder=null;activeSet=null;
    const recentSets=(data.recent||[]).map(item=>setById(item.setId)).filter(Boolean).filter((set,index,list)=>list.findIndex(candidate=>candidate.id===set.id)===index).slice(0,4);
    if(view==='recent'){
      $('#content').innerHTML=`<div class="page-heading"><div><h1 class="page-title">Zuletzt gelernt</h1><p class="page-subtitle">Setze deine letzten Lernrunden fort.</p></div></div>${recentSets.length?`<div class="set-grid">${recentSets.map(setCard).join('')}</div>`:empty('Noch keine Lernsession','Wenn du ein Set lernst, erscheint es hier wieder.','◷')}`;
      bindSetCards();return;
    }
    const subjectCards=data.subjects.map((item,index)=>{
      const sets=subjectSets(item.id),cards=sets.reduce((sum,set)=>sum+setCards(set.id).length,0);
      return `<article class="subject-card" tabindex="0" data-open-subject="${esc(item.id)}" style="--dot:${safeColor(item.color,colors[index%colors.length])}"><div class="subject-card-top"><span class="subject-icon">${esc(item.emoji||icons[index%icons.length])}</span></div><h2>${esc(item.name)}</h2><p>${sets.length} ${sets.length===1?'Set':'Sets'} · ${cards} ${cards===1?'Karte':'Karten'}</p><span class="card-arrow" aria-hidden="true">→</span></article>`;
    }).join('');
    const recentSection=recentSets.length?`<section class="recent-section"><div class="section-head"><h2>Zuletzt gelernt</h2><button class="text-button" data-view="recent">Alle anzeigen</button></div><div class="recent-list">${recentSets.map(set=>`<button class="recent-item" data-open-set="${esc(set.id)}"><span>${esc(set.name)}</span><small>${esc(subject(set.subjectId)?.name||'Fach')}</small><span aria-hidden="true">→</span></button>`).join('')}</div></section>`:'';
    $('#content').innerHTML=`<div class="page-heading"><div><h1 class="page-title">Dein Lernraum.</h1><p class="page-subtitle">Deine Fächer und alles, was du darin lernst.</p></div><button class="quiet-button" id="home-add-subject">＋ Fach hinzufügen</button></div><section class="library-section"><div class="section-head"><h2>Deine Fächer</h2></div>${data.subjects.length?`<div class="subject-grid">${subjectCards}</div>`:empty('Noch keine Fächer','Lege ein Fach an, um deine Ordner und Lernkartensets zu sammeln.','＋')}</section>${recentSection}${data.subjects.length?`<section class="quick-actions"><button class="text-button" id="home-create-set">＋ Neues Set</button><button class="text-button" id="home-import">Text importieren</button></section>`:''}`;
    $('#home-add-subject')?.addEventListener('click',()=>openEntity('subject'));
    $('#home-create-set')?.addEventListener('click',()=>{if(data.subjects.length)openEntity('set')});
    $('#home-import')?.addEventListener('click',()=>openImport());
    document.querySelectorAll('.content [data-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.view;activeSubject=null;activeFolder=null;activeSet=null;render()}));
    bindSubjectCards();bindSetCards();
  }
  function empty(title,copy,icon){
    const label=activeSet?'Karte hinzufügen':activeFolder?'Neues Set':activeSubject?'Ordner hinzufügen':'Fach hinzufügen';
    return `<div class="empty-state"><span class="empty-state-icon" aria-hidden="true">${icon}</span><h2>${title}</h2><p>${copy}</p><button class="quiet-button" data-empty-action>＋ ${label}</button></div>`;
  }
  function openEmptyAction(){if(view==='recent'){view='library';render();return}if(activeSet)openEntity('card');else if(activeFolder)openEntity('set');else if(activeSubject)openEntity('folder');else openEntity('subject')}
  function bindSubjectCards(){
    document.querySelectorAll('[data-open-subject]').forEach(element=>{
      const open=()=>{activeSubject=element.dataset.openSubject;activeFolder=null;activeSet=null;view='library';render()};
      element.onclick=open;element.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}};
    });
    document.querySelectorAll('[data-empty-action]').forEach(button=>button.onclick=openEmptyAction);
  }
  function setCard(set){
    const parent=folder(set.folderId),sub=subject(set.subjectId),count=setCards(set.id).length;
    return `<article class="set-card" tabindex="0" data-open-set="${esc(set.id)}" style="--dot:${safeColor(sub?.color,colors[0])}"><div class="set-card-meta">${esc(parent?.name||sub?.name||'Fach')}</div><h2>${esc(set.name)}</h2><p>${esc(set.description||'Lernkarten öffnen und verwalten.')}</p><div class="set-card-bottom"><span>${count} ${count===1?'Karte':'Karten'}</span><span class="set-actions"><button data-quick-study="${esc(set.id)}" ${count?'':'disabled'}>${sessionForSet(set.id)?'Fortsetzen':'Lernen'}</button><button data-quick-edit="${esc(set.id)}">Bearbeiten</button></span></div></article>`;
  }
  function bindSetCards(){
    document.querySelectorAll('[data-open-set]').forEach(element=>{
      const open=()=>{activeSet=element.dataset.openSet;const set=setById(activeSet);activeSubject=set?.subjectId||null;activeFolder=set?.folderId||null;render()};
      element.onclick=event=>{if(event.target.closest('button'))return;open()};element.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();open()}};
    });
    document.querySelectorAll('[data-quick-study]').forEach(button=>button.onclick=event=>{event.stopPropagation();beginStudy(button.dataset.quickStudy)});
    document.querySelectorAll('[data-quick-edit]').forEach(button=>button.onclick=event=>{event.stopPropagation();editEntity('set',button.dataset.quickEdit)});
  }
  function folderCard(item){
    const count=subjectSets(item.subjectId).filter(set=>set.folderId===item.id).length;
    return `<article class="folder-card" tabindex="0" data-open-folder="${esc(item.id)}" style="--dot:${safeColor(subject(item.subjectId)?.color,colors[0])}"><span class="folder-icon" aria-hidden="true">▱</span><div class="folder-card-copy"><h3>${esc(item.name)}</h3><p>${count} ${count===1?'Set':'Sets'}</p></div><div class="folder-actions"><button class="icon-button" data-edit-folder="${esc(item.id)}" aria-label="${esc(item.name)} umbenennen" title="Umbenennen">✎</button><button class="icon-button" data-delete-folder="${esc(item.id)}" aria-label="${esc(item.name)} löschen" title="Löschen">×</button></div></article>`;
  }
  function bindFolderCards(){
    document.querySelectorAll('[data-open-folder]').forEach(element=>{
      const open=()=>{activeFolder=element.dataset.openFolder;activeSet=null;render()};
      element.onclick=event=>{if(event.target.closest('button'))return;open()};element.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();open()}};
    });
    document.querySelectorAll('[data-edit-folder]').forEach(button=>button.onclick=()=>editEntity('folder',button.dataset.editFolder));
    document.querySelectorAll('[data-delete-folder]').forEach(button=>button.onclick=()=>deleteFolder(button.dataset.deleteFolder));
  }
  function backButton(label){return `<button class="back-button" id="go-back" aria-label="Zurück zu ${esc(label)}"><span aria-hidden="true">←</span><span>${esc(label)}</span></button>`}
  function renderSubject(){
    const item=subject(activeSubject);if(!item){activeSubject=null;return renderLibrary()}
    crumbs(['Dein Lernraum',item.name]);
    const folders=subjectFolders(item.id),looseSets=subjectSets(item.id).filter(set=>!set.folderId);
    const cardCount=subjectSets(item.id).reduce((sum,set)=>sum+setCards(set.id).length,0);
    const folderSection=folders.length?`<div class="folder-grid">${folders.map(folderCard).join('')}</div>`:'';
    const looseSection=looseSets.length?`<div class="section-head"><h2>Sets ohne Ordner</h2></div><div class="set-grid">${looseSets.map(setCard).join('')}</div>`:'';
    $('#content').innerHTML=`<div class="subpage-heading">${backButton('Dein Lernraum')}<div class="subject-heading" style="--dot:${safeColor(item.color,colors[0])}"><span class="subject-icon">${esc(item.emoji||'📚')}</span><div><h1 class="page-title">${esc(item.name)}</h1><p class="page-subtitle">${esc(item.description||`${subjectSets(item.id).length} Sets · ${cardCount} Karten`)}</p></div></div><div class="page-actions"><button class="quiet-button" id="edit-subject">Bearbeiten</button><button class="quiet-button" id="delete-subject">Löschen</button></div></div><section class="library-section"><div class="section-head"><h2>Ordner</h2><button class="quiet-button" id="add-folder">＋ Ordner</button></div>${folderSection||empty('Noch keine Ordner','Lege einen Ordner an, um deine Sets thematisch zu ordnen.','▱')}</section>${looseSection}<div class="quick-actions"><button class="text-button" id="subject-new-set">＋ Neues Set</button></div>`;
    $('#go-back').onclick=()=>{activeSubject=null;activeFolder=null;render()};$('#edit-subject').onclick=()=>editEntity('subject',item.id);$('#delete-subject').onclick=()=>deleteSubject(item.id);$('#add-folder').onclick=()=>openEntity('folder');$('#subject-new-set').onclick=()=>openEntity('set');
    bindFolderCards();bindSetCards();bindSubjectCards();
  }
  function renderFolder(){
    const item=folder(activeFolder);if(!item){activeFolder=null;return renderSubject()}
    const parent=subject(item.subjectId);if(!parent){activeFolder=null;return renderLibrary()}
    const sets=subjectSets(parent.id).filter(set=>set.folderId===item.id);crumbs(['Dein Lernraum',parent.name,item.name]);
    $('#content').innerHTML=`<div class="subpage-heading">${backButton(parent.name)}<div><div class="page-context">${esc(parent.name)}</div><h1 class="page-title">${esc(item.name)}</h1><p class="page-subtitle">${sets.length} ${sets.length===1?'Lernkartenset':'Lernkartensets'} in diesem Ordner.</p></div><div class="page-actions"><button class="quiet-button" id="edit-folder-current">Umbenennen</button><button class="quiet-button" id="delete-folder-current">Löschen</button></div></div><section class="library-section"><div class="section-head"><h2>Lernkartensets</h2><button class="quiet-button" id="folder-new-set">＋ Neues Set</button></div>${sets.length?`<div class="set-grid">${sets.map(setCard).join('')}</div>`:empty('Noch keine Lernkartensets','Erstelle ein Set in diesem Ordner, um Karten hinzuzufügen.','▤')}</section>`;
    $('#go-back').onclick=()=>{activeFolder=null;render()};$('#edit-folder-current').onclick=()=>editEntity('folder',item.id);$('#delete-folder-current').onclick=()=>deleteFolder(item.id);$('#folder-new-set').onclick=()=>openEntity('set');bindSetCards();bindSubjectCards();
  }
  function renderSet(){
    const item=setById(activeSet);if(!item){activeSet=null;return render()}
    const parent=subject(item.subjectId),parentFolder=folder(item.folderId),cards=setCards(item.id);
    crumbs(['Dein Lernraum',parent?.name||'Fach',...(parentFolder?[parentFolder.name]:[]),item.name]);
    const previous=parentFolder?.name||parent?.name||'Zurück';
    const progress=window.WortwerkModel.getSetProgress(cards);
    const studyLabel=sessionForSet(item.id)?'Fortsetzen':'Lernen';
    $('#content').innerHTML=`<div class="subpage-heading">${backButton(previous)}<div><div class="page-context">${esc(parentFolder?.name||parent?.name||'Lernkartenset')}</div><h1 class="page-title">${esc(item.name)}</h1><p class="page-subtitle">${esc(item.description||`${cards.length} Lernkarten`)}</p></div><div class="page-actions"><button class="quiet-button" id="edit-set">Bearbeiten</button><button class="quiet-button" id="delete-set">Löschen</button></div></div>${cards.length?`<div class="study-banner"><div><h2>Lernrunde</h2><p>${cards.length} Karten · ${progress.secure} sicher · ${progress.practice} zu üben · ${progress.new} neu</p></div><div class="study-banner-actions"><button class="primary-button" id="start-study">${studyLabel}</button><button class="quiet-button" id="reset-progress">Lernstapel zurücksetzen</button></div></div>`:''}<section class="library-section"><div class="section-head"><h2>Lernkarten <span class="count-label">${cards.length}</span></h2><div class="section-actions"><button class="quiet-button" id="import-this">Text importieren</button><button class="quiet-button" id="add-card">＋ Karte</button></div></div>${cards.length?`<div class="card-list">${cards.map((card,index)=>{const progress=window.WortwerkModel.getCardProgress(card),label=progress.state==='secure'?'Sicher':progress.state==='practice'?'Zu üben':'Neu';return `<div class="flash-row"><div class="term"><span>${esc(card.front)}</span><small class="flash-progress">${label} · ${progress.attempts} ${progress.attempts===1?'Versuch':'Versuche'}</small></div><div class="definition">${esc(card.back)}</div><div class="row-actions"><button data-move-card="${esc(card.id)}" data-direction="-1" aria-label="Karte nach oben verschieben" title="Nach oben" ${index===0?'disabled':''}>↑</button><button data-move-card="${esc(card.id)}" data-direction="1" aria-label="Karte nach unten verschieben" title="Nach unten" ${index===cards.length-1?'disabled':''}>↓</button><button data-edit-card="${esc(card.id)}" aria-label="Karte bearbeiten" title="Bearbeiten">✎</button><button data-delete-card="${esc(card.id)}" aria-label="Karte löschen" title="Löschen">×</button></div></div>`}).join('')}</div>`:empty('Noch keine Lernkarten','Erstelle eine Karte oder importiere mehrere Begriffe aus Text.','▤')}</section>`;
    $('#go-back').onclick=()=>{activeSet=null;activeFolder=item.folderId||null;render()};$('#edit-set').onclick=()=>editEntity('set',item.id);$('#delete-set').onclick=()=>deleteSet(item.id);$('#start-study')?.addEventListener('click',()=>beginStudy(item.id));$('#reset-progress')?.addEventListener('click',()=>openResetProgress(item.id));$('#add-card').onclick=()=>openEntity('card');$('#import-this').onclick=()=>openImport(item.id);
    document.querySelectorAll('[data-move-card]').forEach(button=>button.onclick=()=>moveCard(button.dataset.moveCard,Number(button.dataset.direction)));
    document.querySelectorAll('[data-edit-card]').forEach(button=>button.onclick=()=>editCard(button.dataset.editCard));document.querySelectorAll('[data-delete-card]').forEach(button=>button.onclick=()=>deleteCard(button.dataset.deleteCard));bindSubjectCards();
  }
  function openEntity(type){formContext={type};fillForm(type);$('#form-dialog').showModal()}
  function editEntity(type,key){formContext={type,key};fillForm(type, type==='subject'?subject(key):type==='folder'?folder(key):setById(key));$('#form-dialog').showModal()}
  function fillForm(type,entity){const title=entity?`Bearbeite ${{subject:'Fach',folder:'Ordner',set:'Set',card:'Lernkarte'}[type]}`:({subject:'Fach anlegen',folder:'Ordner anlegen',set:'Lernkartenset erstellen',card:'Lernkarte erstellen'})[type];$('#form-title').textContent=title;$('#form-eyebrow').textContent=entity?'BEARBEITEN':'NEU IN DEINER BIBLIOTHEK';$('#form-submit').textContent=entity?'Speichern':'Erstellen';let fields='';const input=(name,label,value='',placeholder='')=>`<label class="field-label" for="f-${name}">${label}</label><input id="f-${name}" name="${name}" value="${esc(value)}" placeholder="${esc(placeholder)}" maxlength="100" required>`;
    if(type==='subject'){const selectedColor=entity?.color||colors[data.subjects.length%colors.length],selectedEmoji=entity?.emoji||'📚';fields=input('name','Fachname',entity?.name,'z. B. Französisch')+`<label class="field-label" for="f-description">Beschreibung <span style="color:#71808b">(optional)</span></label><input id="f-description" name="description" value="${esc(entity?.description||'')}" maxlength="160" placeholder="Was möchtest du in diesem Fach lernen?"><span class="field-label" id="color-label">Akzentfarbe</span><input type="hidden" id="f-color" name="color" value="${esc(selectedColor)}"><div class="color-palette" role="group" aria-labelledby="color-label">${palette.map(([hex,name])=>`<button type="button" class="color-swatch ${hex===selectedColor?'selected':''}" data-color="${hex}" aria-label="${name}" aria-pressed="${hex===selectedColor}" title="${name}" style="--swatch:${hex}"></button>`).join('')}</div><span class="field-label" id="emoji-label">Emoji</span><input type="hidden" id="f-emoji" name="emoji" value="${esc(selectedEmoji)}"><label class="emoji-entry-wrap"><span class="emoji-current" id="emoji-current" aria-hidden="true">${esc(selectedEmoji)}</span><input id="emoji-entry" type="text" value="${esc(selectedEmoji)}" maxlength="20" aria-label="Eigenes Emoji eingeben" autocomplete="off"></label><div class="field-hint">Suche ein Emoji oder wähle eines aus. Auf dem Mac öffnet Ctrl + Cmd + Leertaste die vollständige Emoji- und Symbolübersicht.</div><label class="emoji-search-label"><span class="sr-only">Emoji suchen</span><input id="emoji-search" type="search" placeholder="Emoji suchen …" autocomplete="off"></label><div class="emoji-grid" role="group" aria-labelledby="emoji-label">${emojiChoices.map(([emoji,keywords,category])=>`<button type="button" class="emoji-option ${emoji===selectedEmoji?'selected':''}" data-emoji="${esc(emoji)}" data-search="${esc((keywords+' '+category).toLocaleLowerCase('de'))}" aria-label="${esc(keywords.split(' ')[0])}" aria-pressed="${emoji===selectedEmoji}">${emoji}</button>`).join('')}</div>`}
    if(type==='folder')fields=input('name','Ordnername',entity?.name||'','z. B. Kapitel 1')+`<div class="field-hint">Ordner helfen dir, Sets innerhalb eines Fachs zu gruppieren.</div>`;
    if(type==='set'){const subjectId=entity?.subjectId||activeSubject||'',subjectChoice=!entity&&!activeSubject?`<label class="field-label" for="f-subject">Fach</label><select id="f-subject" name="subjectId" required><option value="">Fach auswählen</option>${data.subjects.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select>`:'';fields=subjectChoice+input('name','Name des Sets',entity?.name,'z. B. Vokabeln · Kapitel 3')+`<label class="field-label" for="f-description">Beschreibung <span style="color:#71808b">(optional)</span></label><input id="f-description" name="description" value="${esc(entity?.description||'')}" maxlength="160" placeholder="Thema oder Lernziel"><label class="field-label" for="f-folder">Ordner <span style="color:#71808b">(optional)</span></label><select id="f-folder" name="folderId"><option value="">Ohne Ordner</option>${subjectFolders(subjectId).map(f=>`<option value="${esc(f.id)}" ${(entity?.folderId??activeFolder)===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select>`}
    if(type==='card'){const c=entity;fields=`<label class="field-label" for="f-front">Vorderseite</label><textarea id="f-front" name="front" rows="3" maxlength="2000" required placeholder="Begriff, Frage oder Wort">${esc(c?.front||'')}</textarea><label class="field-label" for="f-back">Rückseite</label><textarea id="f-back" name="back" rows="3" maxlength="3000" required placeholder="Übersetzung, Antwort oder Erklärung">${esc(c?.back||'')}</textarea><div class="field-hint">Tipp: Mit Zeilenumbrüchen kannst du längere Erklärungen übersichtlich formatieren.</div>`}
    $('#form-fields').innerHTML=fields;if(type==='subject')bindSubjectAppearance();if(type==='set')bindSetSubject();$('#form-submit').onclick=e=>{e.preventDefault();submitEntity()};$('#entity-form').onsubmit=e=>{e.preventDefault();submitEntity()}}
  function bindSetSubject(){const selector=$('#f-subject');if(!selector)return;selector.addEventListener('change',()=>{$('#f-folder').innerHTML=`<option value="">Ohne Ordner</option>${subjectFolders(selector.value).map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}`})}
  function bindSubjectAppearance(){const colorInput=$('#f-color'),emojiInput=$('#f-emoji'),emojiEntry=$('#emoji-entry'),current=$('#emoji-current'),palette=$('.color-palette'),grid=$('.emoji-grid');palette.querySelectorAll('[data-color]').forEach(button=>button.onclick=()=>{colorInput.value=button.dataset.color;palette.querySelectorAll('[data-color]').forEach(item=>{const selected=item===button;item.classList.toggle('selected',selected);item.setAttribute('aria-pressed',String(selected))})});const chooseEmoji=value=>{const emoji=value.trim()||'📚';emojiInput.value=emoji;current.textContent=emoji;grid.querySelectorAll('[data-emoji]').forEach(button=>{const selected=button.dataset.emoji===emoji;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected))})};emojiEntry.addEventListener('input',()=>chooseEmoji(emojiEntry.value));grid.querySelectorAll('[data-emoji]').forEach(button=>button.onclick=()=>{emojiEntry.value=button.dataset.emoji;chooseEmoji(button.dataset.emoji)});$('#emoji-search').addEventListener('input',e=>{const query=e.target.value.trim().toLocaleLowerCase('de');grid.querySelectorAll('[data-emoji]').forEach(button=>{button.hidden=!!query&&!button.dataset.search.includes(query)})})}
  function submitEntity(){const type=formContext?.type;const form=$('#entity-form');if(!form.reportValidity())return;const fd=new FormData(form);if(type==='subject'){const v={name:fd.get('name').trim(),description:fd.get('description').trim(),color:fd.get('color'),emoji:fd.get('emoji')||'📚'};if(!v.name){toast('Der Fachname darf nicht leer sein.');return} if(formContext.key)Object.assign(subject(formContext.key),v,{updatedAt:new Date().toISOString()});else{const timestamp=new Date().toISOString();const s={id:id(),...v,icon:v.emoji,createdAt:timestamp,updatedAt:timestamp};data.subjects.push(s);activeSubject=s.id;activeFolder=null}}
    if(type==='folder'){const name=fd.get('name').trim();if(!name){toast('Der Ordnername darf nicht leer sein.');return}if(!activeSubject||!subject(activeSubject)){toast('Wähle zuerst ein Fach für den Ordner.');return}if(formContext.key)Object.assign(folder(formContext.key),{name,updatedAt:new Date().toISOString()});else{const timestamp=new Date().toISOString();data.folders.push({id:id(),name,subjectId:activeSubject,createdAt:timestamp,updatedAt:timestamp})}}
    if(type==='set'){const existing=formContext.key?setById(formContext.key):null,subjectId=existing?.subjectId||fd.get('subjectId')||activeSubject,folderId=fd.get('folderId')||null,v={name:fd.get('name').trim(),description:fd.get('description').trim(),folderId};if(!v.name){toast('Der Setname darf nicht leer sein.');return}if(!subjectId||!subject(subjectId)){toast('Wähle ein Fach für dieses Set.');return}if(folderId&&folder(folderId)?.subjectId!==subjectId){toast('Der ausgewählte Ordner gehört nicht zu diesem Fach.');return}if(existing){Object.assign(existing,v,{updatedAt:new Date().toISOString()})}else{const timestamp=new Date().toISOString(),created={id:id(),...v,subjectId,createdAt:timestamp,updatedAt:timestamp};data.sets.push(created);activeSet=created.id;activeFolder=folderId}activeSubject=subjectId}
    if(type==='card'){const v={front:fd.get('front').trim(),back:fd.get('back').trim()},timestamp=new Date().toISOString();if(!v.front||!v.back){toast('Vorder- und Rückseite dürfen nicht leer sein.');return}if(formContext.key)Object.assign(data.cards.find(c=>c.id===formContext.key),v,{updatedAt:timestamp});else data.cards.push({id:id(),setId:activeSet,...v,position:setCards(activeSet).length,correctCount:0,incorrectCount:0,attemptCount:0,lastReviewedAt:null,nextReviewAt:null,createdAt:timestamp,updatedAt:timestamp});const s=setById(activeSet);if(s)s.updatedAt=timestamp}
    save();$('#form-dialog').close();render()}
  function moveCard(key,direction){const cards=setCards(activeSet),index=cards.findIndex(card=>card.id===key),next=index+direction;if(index<0||next<0||next>=cards.length)return;[cards[index],cards[next]]=[cards[next],cards[index]];const timestamp=new Date().toISOString();cards.forEach((card,position)=>{card.position=position;card.updatedAt=timestamp});save();render()}
  function editCard(key){const c=data.cards.find(x=>x.id===key);if(!c)return;formContext={type:'card',key};fillForm('card',c);$('#form-dialog').showModal()}
  function deleteCard(key){const card=data.cards.find(c=>c.id===key);if(!card||!confirm('Diese Lernkarte dauerhaft löschen?'))return;data.cards=data.cards.filter(c=>c.id!==key);setCards(card.setId).forEach((remaining,position)=>{remaining.position=position});save();render()}
  function deleteSubject(key){const s=subject(key);if(!s||!confirm(`„${s.name}“ mit allen Ordnern, Sets und Karten löschen?`))return;const setIds=data.sets.filter(x=>x.subjectId===key).map(x=>x.id);data.subjects=data.subjects.filter(x=>x.id!==key);data.folders=data.folders.filter(x=>x.subjectId!==key);data.sets=data.sets.filter(x=>x.subjectId!==key);data.cards=data.cards.filter(x=>!setIds.includes(x.setId));data.recent=data.recent.filter(r=>!setIds.includes(r.setId));for(const setId of setIds)delete data.studySessions[setId];data.studyHistory=data.studyHistory.filter(entry=>!setIds.includes(entry.setId));activeSubject=null;activeFolder=null;activeSet=null;save();render();toast('Fach gelöscht')}
  function deleteFolder(key){const f=folder(key);if(!f||!confirm(`Ordner „${f.name}“ löschen? Zugehörige Sets bleiben im Fach.`))return;data.folders=data.folders.filter(x=>x.id!==key);data.sets.forEach(s=>{if(s.folderId===key)s.folderId=null});if(activeFolder===key)activeFolder=null;save();render();toast('Ordner gelöscht')}
  function deleteSet(key){const s=setById(key);if(!s||!confirm(`„${s.name}“ und alle zugehörigen Karten löschen?`))return;data.sets=data.sets.filter(x=>x.id!==key);data.cards=data.cards.filter(c=>c.setId!==key);data.recent=data.recent.filter(r=>r.setId!==key);delete data.studySessions[key];data.studyHistory=data.studyHistory.filter(entry=>entry.setId!==key);activeSet=null;save();render();toast('Set gelöscht')}
  function parseImport(text){return window.WortwerkParser.parseImport(text)}
  function openImport(targetSet){if(!data.sets.length){toast('Erstelle zuerst ein Set für den Import.');return}$('#import-text').value='';$('#import-file').value='';$('#import-file-name').textContent='TXT · UTF-8';const select=$('#import-set');select.innerHTML=data.sets.map(s=>`<option value="${esc(s.id)}" ${targetSet===s.id?'selected':''}>${esc(subject(s.subjectId)?.name||'Fach')} · ${esc(s.name)}</option>`).join('');importRows=[];$('#import-preview').innerHTML='';$('#import-submit').disabled=true;$('#import-submit').textContent='0 Karten erstellen';$('#import-dialog').showModal()}
  function updateImportPreview(){const result=parseImport($('#import-text').value);importRows=result.rows.map(row=>({...row}));const preview=$('#import-preview');const rows=importRows.map((r,i)=>`<div class="preview-line editable-preview"><span class="preview-index">${r.line}</span><input aria-label="Vorderseite Zeile ${r.line}" data-import-front="${i}" value="${esc(r.front)}"><input aria-label="Rückseite Zeile ${r.line}" data-import-back="${i}" value="${esc(r.back)}"><button type="button" class="row-remove" data-import-remove="${i}" aria-label="Karte aus Vorschau entfernen">×</button></div>`).join('');const errors=result.errors.map(e=>`<div class="preview-line bad"><span class="preview-index">Zeile ${e.line}</span><span style="grid-column:span 3"><strong>${esc(e.reason)}</strong><br><code>${esc(e.text)}</code></span></div>`).join('');preview.innerHTML=(result.rows.length||result.errors.length)?`<div class="preview-head"><span>IMPORT-VORSCHAU</span><span>${result.rows.length} Karten · ${result.errors.length} Fehler</span></div>${rows}${errors}`:'';$('#import-submit').disabled=result.rows.length===0||result.errors.length>0;$('#import-submit').textContent=result.errors.length?'Fehler beheben':`${result.rows.length} Karten erstellen`}
  $('#import-text').addEventListener('input',()=>{importRows=[];$('#import-submit').disabled=true;$('#import-submit').textContent='Import erst prüfen';$('#import-preview').innerHTML=$('#import-text').value.trim()?'<p class="field-hint">Text geändert. Klicke auf „Import prüfen“, um die Vorschau zu aktualisieren.</p>':''});
  $('#preview-import').addEventListener('click',updateImportPreview);
  $('#import-preview').addEventListener('input',e=>{const f=e.target.dataset.importFront,b=e.target.dataset.importBack;if(f!==undefined)importRows[Number(f)].front=e.target.value;if(b!==undefined)importRows[Number(b)].back=e.target.value;$('#import-submit').disabled=importRows.length===0||parseImport($('#import-text').value).errors.length>0||importRows.some(r=>!r.front.trim()||!r.back.trim());if(importRows.some(r=>!r.front.trim()||!r.back.trim()))$('#import-submit').textContent='Leere Seiten beheben'});
  $('#import-preview').addEventListener('click',e=>{const i=e.target.dataset.importRemove;if(i===undefined)return;importRows.splice(Number(i),1);e.target.closest('.preview-line').remove();$('#import-preview').querySelectorAll('.editable-preview').forEach((row,index)=>{row.querySelector('[data-import-front]').dataset.importFront=index;row.querySelector('[data-import-back]').dataset.importBack=index;row.querySelector('[data-import-remove]').dataset.importRemove=index});$('#import-submit').textContent=`${importRows.length} Karten erstellen`;$('#import-submit').disabled=importRows.length===0||parseImport($('#import-text').value).errors.length>0});
  $('#import-file').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;$('#import-file-name').textContent=file.name;try{$('#import-text').value=await file.text();updateImportPreview()}catch(error){console.error('Textdatei konnte nicht gelesen werden.',error);toast('Die Textdatei konnte nicht gelesen werden.')} });
  $('#entity-form [value="cancel"]').addEventListener('click',()=>$('#form-dialog').close());
  $('#import-form [value="cancel"]').addEventListener('click',()=>$('#import-dialog').close());
  $('#import-submit').addEventListener('click',e=>{e.preventDefault();const setId=$('#import-set').value;if(!setById(setId)||!importRows.length||parseImport($('#import-text').value).errors.length||importRows.some(row=>!row.front.trim()||!row.back.trim()))return;const timestamp=new Date().toISOString(),position=setCards(setId).length,newCards=window.WortwerkModel.createImportedCards(importRows,{setId,position,timestamp,createId:id});data.cards=data.cards.concat(newCards);setById(setId).updatedAt=timestamp;save();$('#import-dialog').close();if(activeSet===setId)render();toast(`${newCards.length} Karten erstellt`)});
  function sessionForSet(key){return data.studySessions?.[key]||null}
  let resetSetId = null;
  function openResetProgress(key){
    const item=setById(key),cards=setCards(key);if(!item||!cards.length)return;
    resetSetId=key;$('#reset-progress-copy').textContent=`Der Lernfortschritt für „${item.name}“ wird vollständig zurückgesetzt. Du beginnst danach wieder bei Karte 1. Karten, Reihenfolge, Inhalte und Set-Einstellungen bleiben erhalten.`;
    $('#reset-progress-dialog').showModal();$('#reset-progress-cancel').focus();
  }
  async function confirmResetProgress(){
    const key=resetSetId;if(!key||!setById(key))return;
    const count=window.WortwerkModel.resetSetProgress(data,key);resetSetId=null;
    $('#reset-progress-dialog').close();render();
    try{await save();toast(`Lernstapel zurückgesetzt · ${count} ${count===1?'Karte':'Karten'} wieder neu`)}catch(error){console.error('Lernfortschritt konnte nicht dauerhaft zurückgesetzt werden.',error);toast('Zurücksetzen lokal angewendet, aber nicht mit Supabase gespeichert. Bitte Verbindung prüfen.')}
  }
  $('#reset-progress-form').addEventListener('submit',event=>event.preventDefault());
  $('#reset-progress-confirm').addEventListener('click',confirmResetProgress);
  $('#reset-progress-cancel').addEventListener('click',()=>{$('#reset-progress-dialog').close();resetSetId=null});
  $('#reset-progress-close').addEventListener('click',()=>{$('#reset-progress-dialog').close();resetSetId=null});
  $('#reset-progress-dialog').addEventListener('close',()=>{resetSetId=null});
  function completeSession(record){if(session?.completionRecorded)return;delete data.studySessions[record.setId];data.studyHistory.unshift(window.WortwerkModel.summarizeSession(record,new Date().toISOString()));data.studyHistory=data.studyHistory.slice(0,30);if(session)session.completionRecorded=true;save()}
  function saveSessionProgress(nextIndex=session?.index){
    if(!session)return;
    const record={id:session.id,setId:session.setId,startedAt:session.startedAt,cardIds:session.cards.map(card=>card.id),results:session.results.slice(),index:Math.max(0,Math.min(nextIndex,session.cards.length-1))};
    if(session.results.every(result=>result!==null)){completeSession(record);return}
    data.studySessions[session.setId]=record;save();
  }
  function beginStudy(key){
    const cards=setCards(key);if(!cards.length){toast('Dieses Set enthält noch keine Karten.');return}
    session=null;
    const saved=sessionForSet(key);
    if(saved){const byId=new Map(cards.map(card=>[card.id,card])),paired=saved.cardIds.map((cardId,index)=>({card:byId.get(cardId),result:saved.results[index]})).filter(item=>item.card);if(paired.length)session={id:saved.id,setId:key,startedAt:saved.startedAt,cards:paired.map(item=>item.card),index:Math.min(saved.index,paired.length-1),flipped:false,results:paired.map(item=>item.result)}}
    if(!session)session={id:id(),setId:key,startedAt:new Date().toISOString(),cards:cards.slice(),index:0,flipped:false,results:Array(cards.length).fill(null)};
    data.recent.unshift({setId:key,at:new Date().toISOString()});data.recent=data.recent.slice(0,30);saveSessionProgress();
    $('#study-title').textContent=setById(key)?.name||'Lernsession';$('#study-complete').hidden=true;$('#shuffle-toggle').setAttribute('aria-pressed','false');$('#study-dialog').classList.remove('is-fullscreen');$('#study-dialog').showModal();renderStudyCard();
  }
  function updateStudyScoreCounts(){if(!session)return;const known=session.results.filter(result=>result===true).length,missed=session.results.filter(result=>result===false).length;$('#known-count').textContent=String(known);$('#missed-count').textContent=String(missed);$('#study-known').textContent=`${known} ✓ · ${missed} ✕`;$('#answer-yes').setAttribute('aria-label',`Gewusst, bisher ${known}`);$('#answer-no').setAttribute('aria-label',`Nicht gewusst, bisher ${missed}`)}
  function renderStudyCard(options={}){if(!session)return;const {resetOrientation=false,keepTransition=false}=options,total=session.cards.length,index=session.index,card=session.cards[index],studyCard=$('#study-card'),swipeLayer=$('#study-card-swipe-layer'),inner=$('#study-card-inner'),nextCard=$('#study-next-card');if(!keepTransition)nextCard.classList.remove('is-visible');$('#study-progress-label').textContent=`${index+1} von ${total}`;const reviewed=session.results.filter(result=>result!==null).length;$('#study-progress-bar').style.width=`${Math.round(reviewed/total*100)}%`;$('#study-progress-track').setAttribute('aria-valuemax',String(total));$('#study-progress-track').setAttribute('aria-valuenow',String(reviewed));updateStudyScoreCounts();
    const result=session.results[index];$('#session-stat').textContent=result===null?'Noch nicht bewertet':result?'Diese Karte: gewusst':'Diese Karte: noch üben';if(resetOrientation)inner.classList.add('no-flip-transition');inner.classList.toggle('flipped',session.flipped);if(resetOrientation)requestAnimationFrame(()=>inner.classList.remove('no-flip-transition'));$('#card-front').textContent=card.front;$('#card-back').textContent=card.back;studyCard.setAttribute('aria-label',session.flipped?'Rückseite: '+card.back:'Vorderseite: '+card.front);studyCard.setAttribute('aria-pressed',String(session.flipped));if(!keepTransition){studyCard.classList.toggle('is-final-card',index===total-1);studyCard.disabled=false;swipeLayer.classList.remove('is-swiping');$('#answer-no').disabled=false;$('#answer-yes').disabled=false;$('#study-prev').disabled=index===0;$('#study-next').disabled=false}}
  function flip(){if(!session||session.transitioning||!$('#study-complete').hidden)return;session.flipped=!session.flipped;renderStudyCard()}
  function moveStudy(delta){if(!session||session.transitioning||!$('#study-complete').hidden)return;const next=session.index+delta;if(next<0||next>=session.cards.length)return;session.index=next;session.flipped=false;saveSessionProgress();renderStudyCard()}
  function nextStudyCard(){if(!session||session.transitioning||!$('#study-complete').hidden)return;if(session.index<session.cards.length-1){moveStudy(1);return}const next=window.WortwerkModel.nextUnratedIndex(session.results,session.index);if(next>=0){session.index=next;session.flipped=false;saveSessionProgress();renderStudyCard()}else finishStudy()}
  function scoreCard(known){
    if(!session||session.transitioning||!$('#study-complete').hidden)return;
    const activeSession=session,card=session.cards[session.index],timestamp=new Date().toISOString();
    session.transitioning=true;
    window.WortwerkModel.recordCardAnswer(card,known,timestamp);session.results[session.index]=known;
    const nextIndex=window.WortwerkModel.nextUnratedIndex(session.results,session.index),hasNext=nextIndex>=0;
    saveSessionProgress(hasNext?nextIndex:session.index);
    updateStudyScoreCounts();
    const studyCard=$('#study-card'),swipeLayer=$('#study-card-swipe-layer'),nextCard=$('#study-next-card');
    $('#session-stat').textContent=known?'Gewusst':'Noch zu üben';
    studyCard.classList.toggle('is-final-card',!hasNext);
    swipeLayer.classList.add('is-swiping');
    studyCard.disabled=true;$('#answer-no').disabled=true;$('#answer-yes').disabled=true;$('#study-prev').disabled=true;$('#study-next').disabled=true;
    if(hasNext){$('#next-card-front').textContent=session.cards[nextIndex].front;nextCard.classList.add('is-visible')}
    let completed=false,fallback;
    const finishTransition=()=>{
      if(completed||session!==activeSession)return;
      completed=true;clearTimeout(fallback);swipeLayer.removeEventListener('animationend',onAnimationEnd);
      if(hasNext){session.index=nextIndex;session.flipped=false;renderStudyCard({resetOrientation:true,keepTransition:true})}
      swipeLayer.classList.remove('is-swiping');nextCard.classList.remove('is-visible');session.transitioning=false;
      if(!hasNext)finishStudy();else renderStudyCard()
    };
    const onAnimationEnd=event=>{if(event.target===swipeLayer&&!event.pseudoElement&&event.animationName==='card-swipe-away')finishTransition()};
    swipeLayer.addEventListener('animationend',onAnimationEnd);
    fallback=window.setTimeout(finishTransition,window.matchMedia('(prefers-reduced-motion: reduce)').matches?100:820);
  }
  function finishStudy(){if(!session)return;if(!session.completionRecorded)completeSession({id:session.id,setId:session.setId,startedAt:session.startedAt,cardIds:session.cards.map(card=>card.id),results:session.results});const {known,missed,unrated,percentage}=window.WortwerkModel.summarizeResults(session.results);const evaluated=known+missed,circumference=2*Math.PI*42,knownLength=circumference*(evaluated?known/evaluated:0),missedLength=circumference*(evaluated?missed/evaluated:0);$('#study-progress-bar').style.width='100%';$('#study-progress-track').setAttribute('aria-valuenow',String(session.cards.length));$('#complete-copy').textContent=`${evaluated} von ${session.cards.length} Karten bewertet`;$('#score-value').textContent=`${percentage}%`;$('#score-ring-known').style.strokeDasharray=`${knownLength} ${circumference-knownLength}`;$('#score-ring-missed').style.strokeDasharray=`${missedLength} ${circumference-missedLength}`;$('#score-ring-missed').style.strokeDashoffset=String(-knownLength);$('#result-chart').setAttribute('aria-label',`${percentage} Prozent richtig: ${known} gewusst und ${missed} noch zu üben`);$('#result-known').textContent=String(known);$('#result-missed').textContent=String(missed);$('#result-unrated').textContent=String(unrated);$('#retry-missed').hidden=missed===0;$('#study-complete').hidden=false}
  function retryMissed(){if(!session)return;const cards=session.cards.filter((card,index)=>session.results[index]===false);if(!cards.length)return;session={id:id(),setId:session.setId,startedAt:new Date().toISOString(),cards,index:0,flipped:false,results:Array(cards.length).fill(null)};saveSessionProgress();$('#study-title').textContent=`Wiederholung · ${setById(session.setId)?.name||'Lernsession'}`;$('#study-complete').hidden=true;$('#shuffle-toggle').setAttribute('aria-pressed','false');renderStudyCard()}
  const studyDialog=$('#study-dialog');
  function syncFullscreenButton(){const active=document.fullscreenElement===studyDialog||studyDialog.classList.contains('is-fullscreen'),button=$('#study-expand');button.setAttribute('aria-pressed',String(active));button.setAttribute('aria-label',active?'Vollbild verlassen':'Lernmodus im Vollbild öffnen');button.title=active?'Vollbild verlassen':'Vollbild';$('#study-expand-label').textContent=active?'Fenster':'Vollbild'}
  async function toggleStudyFullscreen(){if(document.fullscreenElement===studyDialog||studyDialog.classList.contains('is-fullscreen')){studyDialog.classList.remove('is-fullscreen');if(document.fullscreenElement===studyDialog){try{await document.exitFullscreen()}catch(error){console.warn('Vollbildmodus konnte nicht beendet werden.',error)}}syncFullscreenButton();return}try{if(studyDialog.requestFullscreen)await studyDialog.requestFullscreen();else studyDialog.classList.add('is-fullscreen')}catch(error){studyDialog.classList.add('is-fullscreen')}syncFullscreenButton()}
  function endStudy(){const setId=session?.setId;if(document.fullscreenElement===studyDialog)document.exitFullscreen().catch(()=>{});studyDialog.classList.remove('is-fullscreen');studyDialog.close();session=null;syncFullscreenButton();if(setId){const label=sessionForSet(setId)?'Fortsetzen':'Lernen';if(activeSet===setId){const button=$('#start-study');if(button)button.textContent=label}document.querySelectorAll('[data-quick-study]').forEach(button=>{if(button.dataset.quickStudy===setId)button.textContent=label})}}
  studyDialog.addEventListener('fullscreenchange',syncFullscreenButton);
  $('#study-expand').onclick=toggleStudyFullscreen;
  $('#study-card').onclick=flip;$('#answer-no').onclick=()=>scoreCard(false);$('#answer-yes').onclick=()=>scoreCard(true);$('#study-prev').onclick=()=>moveStudy(-1);$('#study-next').onclick=nextStudyCard;$('#study-close').onclick=endStudy;$('#finish-study').onclick=()=>{endStudy();render()};$('#retry-missed').onclick=retryMissed;$('#study-manage').onclick=()=>{endStudy();render()};$('#shuffle-toggle').onclick=()=>{if(!session)return;const paired=session.cards.map((card,index)=>[card,session.results[index]]);for(let i=paired.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[paired[i],paired[j]]=[paired[j],paired[i]]}session.cards=paired.map(pair=>pair[0]);session.results=paired.map(pair=>pair[1]);session.index=0;session.flipped=false;$('#study-complete').hidden=true;$('#shuffle-toggle').setAttribute('aria-pressed','true');saveSessionProgress();renderStudyCard()};
  document.addEventListener('keydown',e=>{if(!$('#study-dialog').open)return;if(e.key==='Escape'){endStudy();return}if(e.target.matches('input,textarea,select,[contenteditable="true"]')||session?.transitioning)return;const focusedButton=e.target.closest('button');if(focusedButton&&focusedButton.id!=='study-card')return;if(e.key===' '){if(focusedButton?.id==='study-card')return;e.preventDefault();flip()}if(e.key==='ArrowLeft'){e.preventDefault();moveStudy(-1)}if(e.key==='ArrowRight'){e.preventDefault();nextStudyCard()}});
  $('#create-set').onclick=()=>{if(!data.subjects.length){openEntity('subject');return}openEntity('set')};$('#import-open').onclick=()=>openImport(activeSet);$('#import-form').onsubmit=e=>e.preventDefault();
  window.addEventListener('library-save-error',()=>toast('Mit Supabase konnte nicht gespeichert werden. Bitte Verbindung prüfen und erneut versuchen.'));
  window.WortwerkReloadLibrary=async()=>{try{data=await window.WortwerkRepository.loadLibrary(window.WortwerkModel.normalizeLibrary);render()}catch(error){console.error('Lernbibliothek konnte nicht geladen werden.',error);$('#content').innerHTML='<section class="empty-state"><h2>Deine Bibliothek konnte nicht geladen werden.</h2><p>Bitte prüfe deine Verbindung und lade die Seite erneut.</p><button class="quiet-button" onclick="location.reload()">Erneut laden</button></section>'}};
  window.WortwerkReloadLibrary();
})();
